default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "behind_the_tap_lite_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "behind_the_tap_lite_test").sub("development", "test") %>
